#!/usr/bin/env node
// Serverless projectInitPre hook script.
// echo "Hookscript: project-init-pre $*"


// 'use strict';

console.log("Hookscript: project-init-pre starting");
console.log(process.argv);
console.log(process.env);

var AWS = require('aws-sdk');

var credentials = new AWS.SharedIniFileCredentials({profile: 'EverTrueAndrew'});
AWS.config.credentials = credentials;

console.log(credentials);

// TODO: figure out why this is needed... sdk should pull from env automatically
// AWS.config.update({
//   accessKeyId: process.env.AWS_ACCESS_KEY_ID,
//   secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
//   region: process.env.AWS_REGION
// });

// var s3bucket = new AWS.S3({
//   params: {
//     Bucket: "gitrdone-evertrue"
//   }
// });

// s3bucket.createBucket(function(err) {
//   console.log("s3 bucket created");
//   if (err) {
//     console.log("s3 bucket create error");
//     console.log(err);
//   }
// });


throw "pre-hook done";
